---
- name: Ensure MariaDB databases are present
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ mariadb_databases }}"
  loop_control:
    label: "{{ item.name }}"
