---
- include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "vars"
      errors: "ignore"
- include_tasks: overwrites.yml

- include_tasks: install.yml
- include_tasks: configure.yml
- include_tasks: security.yml
- include_tasks: databases.yml
- include_tasks: users.yml
